"""Add photo_path and template_name

Revision ID: 0f6775a28f4f
Revises: 08fffc69b378
Create Date: 2025-06-30 12:46:40.712101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6775a28f4f'
down_revision = '08fffc69b378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('template_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('template_name')
        batch_op.drop_column('photo_path')

    # ### end Alembic commands ###
